/**
 * Turns the prepared SVGs in src/icons/svg/ into src/icons/paths.generated.ts.
 *
 * Why codegen rather than vite-plugin-svgr: the gradient treatment needs a
 * <defs> and the <path> inside the SAME <svg> element, per instance, so that
 * `currentColor` in the gradient stops resolves to that icon's own color. An
 * svgr component is opaque — you can't inject a <defs> sibling into it. Storing
 * path data lets GradientIcon assemble the whole <svg> itself.
 *
 * It also enforces the preparation rules, so a raw game-icons download fails
 * loudly here instead of rendering a black square in the app.
 *
 *   npm run icons
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SVG_DIR = join(ROOT, "src", "icons", "svg");
const OUT = join(ROOT, "src", "icons", "paths.generated.ts");

/** game-icons ships a full-bleed background rect as the first path. */
const BG_RECT = /^M0 0h(\d+)v\1H0z$/i;

/**
 * The role names declared in src/icons/index.tsx, read out of the FALLBACK map.
 *
 * A filename that isn't a role generates art nothing can ever look up — the app
 * silently keeps rendering the Material fallback with no error anywhere. That
 * has already happened twice (random.svg, daily.svg), so it fails here instead.
 */
function knownRoles() {
  const src = readFileSync(join(ROOT, "src", "icons", "index.tsx"), "utf8");
  const block = src.match(/export const FALLBACK = \{([\s\S]*?)\n\} as const/);
  if (!block) return null; // registry moved or reshaped; skip rather than block the build
  return new Set([...block[1].matchAll(/^\s*"?([a-z0-9-]+)"?:/gm)].map((m) => m[1]));
}

const ROLES = knownRoles();
const problems = [];
const icons = {};

mkdirSync(SVG_DIR, { recursive: true });
const files = readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg")).sort();

for (const file of files) {
  const role = basename(file, ".svg");
  const raw = readFileSync(join(SVG_DIR, file), "utf8");
  // Strip comments before validating: a prepared file may legitimately *quote*
  // the very patterns we reject, to document what was removed from the original.
  const src = raw.replace(/<!--[\s\S]*?-->/g, "");
  const where = `svg/${file}`;

  if (!/^[a-z0-9-]+$/.test(role)) {
    problems.push(`${where}: name icons by ROLE in kebab-case (e.g. learn.svg), not "${role}"`);
    continue;
  }
  if (ROLES && !ROLES.has(role)) {
    // Token-based, not substring: plain `includes` matched sound-on for
    // threefold-repetition, because "repetiti(on)" contains "on".
    const tokens = new Set(role.split("-"));
    const near = [...ROLES].filter((r) => r.split("-").some((t) => tokens.has(t)));
    problems.push(
      `${where}: "${role}" is not a role in src/icons/index.tsx, so nothing would ever render it.` +
        (near.length ? `\n      Did you mean: ${near.join(", ")}?` : "") +
        `\n      Roles are listed in FALLBACK; rename the file to match one.`,
    );
    continue;
  }

  const viewBox = src.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) {
    problems.push(`${where}: no viewBox — the icon can't scale without one`);
    continue;
  }

  // Every path's `d`, in document order.
  const all = [...src.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  const d = all.filter((p) => !BG_RECT.test(p.trim()));
  if (all.length !== d.length) {
    problems.push(`${where}: background rect found — delete the <path d="M0 0h…v…H0z"> before committing`);
  }
  if (d.length === 0) {
    problems.push(`${where}: no drawable path found`);
    continue;
  }

  // Anything that pins color or size defeats theming; catch it here.
  if (/fill="(?!currentColor|none)[^"]+"/.test(src)) {
    problems.push(`${where}: hardcoded fill — use fill="currentColor" (or drop the attribute)`);
  }
  if (/<svg[^>]*style="[^"]*(?:width|height)/.test(src)) {
    problems.push(`${where}: inline width/height in style — remove it, CSS controls the size`);
  }
  if (/<style[\s>]|class="/.test(src)) {
    problems.push(`${where}: <style> or class attributes collide when an icon inlines repeatedly`);
  }

  icons[role] = { viewBox, d };
}

if (problems.length) {
  console.error("\nIcon preparation problems:\n" + problems.map((p) => "  - " + p).join("\n") + "\n");
  process.exit(1);
}

const body = Object.entries(icons)
  .map(([role, { viewBox, d }]) => {
    const paths = d.map((p) => `      ${JSON.stringify(p)},`).join("\n");
    return `  ${JSON.stringify(role)}: {\n    viewBox: ${JSON.stringify(viewBox)},\n    d: [\n${paths}\n    ],\n  },`;
  })
  .join("\n");

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-icons.mjs — do not edit.
// Add or change icons in src/icons/svg/, then run: npm run icons

export interface IconArt {
  viewBox: string;
  d: string[];
}

export const ICON_ART = {
${body}
} as const satisfies Record<string, IconArt>;

export type IconArtName = keyof typeof ICON_ART;
`,
  "utf8"
);

console.log(`icons: wrote ${Object.keys(icons).length} to src/icons/paths.generated.ts`);
if (!Object.keys(icons).length) console.log("  (drop role-named .svg files into src/icons/svg/ to get started)");
